apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels: {}
  name: jupyterhub-img
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/sonal_23/jupyterhub-img:dev
    from:
      kind: DockerImage
      name: quay.io/sonal_23/jupyterhub-img:dev
    name: latest
    referencePolicy:
      type: Source
